In [1]:
name = "SURYA"
age = 19
height = 6.0
is_student = True

print(f"My name is {name}, I am {age} years old, my height is {height} feet, and it is {is_student} that I am a student.")

My name is SURYA, I am 19 years old, my height is 6.0 feet, and it is True that I am a student.


In [10]:
try:
    num = int(input["Enter an integer: "])

    if num > 0:
        print("The number is positive.")
    elif num < 0:
        print("The number is negative.")
    else:
        print("The number is zero.")
        
except ValueError:
    print("Please enter a valid integer.")


<class 'TypeError'>: 'function' object is not subscriptable

In [15]:
num = int()(input("Enter a number: "))

for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

<class 'TypeError'>: 'int' object is not callable

Enter a number:  11


In [16]:
  num = int(input("Enter a number: "))

for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

<class 'TypeError'>: int() argument must be a string, a bytes-like object or a real number, not 'PyodideFuture'

Enter a number:  12


In [17]:
fruits = ["Apple", "Banana", "Cherry", "Mango", "Orange"]

fruits.append("Grapes")
fruits.remove("Banana")
fruits[2] = "Pineapple"

print("Updated fruit list:", fruits)
print("First fruit:", fruits[0])
print("Last fruit:", fruits[-1])

Updated fruit list: ['Apple', 'Cherry', 'Pineapple', 'Orange', 'Grapes']
First fruit: Apple
Last fruit: Grapes


In [18]:
numbers = (10, 20, 30, 40, 50)

print("Tuple:", numbers)
print("First element:", numbers[0])
print("Last element:", numbers[-1])
print("Sum of all elements:", sum(numbers))
print("Index of 30:", numbers.index(30))

Tuple: (10, 20, 30, 40, 50)
First element: 10
Last element: 50
Sum of all elements: 150
Index of 30: 2


In [19]:
students = {"SURYA": 85, "SHYAM": 92, "ALFY": 78}

students["SURYA"] = 88
students["SHYAM"] = 90
del students["ALFY"]

print("Updated Dictionary:", students)
print("Marks of SHYAM:", students["SHYAM"])
print("All student names:", list(students.keys()))
print("All marks:", list(students.values()))

Updated Dictionary: {'SURYA': 88, 'SHYAM': 90}
Marks of SHYAM: 90
All student names: ['SURYA', 'SHYAM']
All marks: [88, 90]


In [20]:
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

union_set = set1 | set2
intersection_set = set1 & set2
difference_set = set1 - set2
symmetric_difference_set = set1 ^ set2

print("Union:", union_set)
print("Intersection:", intersection_set)
print("Difference (set1 - set2):", difference_set)
print("Symmetric Difference:", symmetric_difference_set)

Union: {1, 2, 3, 4, 5, 6, 7, 8}
Intersection: {4, 5}
Difference (set1 - set2): {1, 2, 3}
Symmetric Difference: {1, 2, 3, 6, 7, 8}


In [21]:
def find_largest(numbers):
    return max(numbers)

sample_list = [10, 25, 67, 89, 45]
largest_number = find_largest(sample_list)

print("Largest number:", largest_number)

Largest number: 89


In [23]:
squares = [x**2 for x in range(2, 21, 2)]
print("Squares of even numbers:", squares)

Squares of even numbers: [4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


In [25]:
product = lambda a, b: a * b

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

print("Product:", product(num1, num2))

<class 'TypeError'>: int() argument must be a string, a bytes-like object or a real number, not 'PyodideFuture'

Enter first number:  1


In [27]:
import numpy as np

one_d = np.array([1, 2, 3, 4, 5])
two_d = np.array([[1, 2, 3], [4, 5, 6]])
three_d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:\n", one_d)
print("Shape:", one_d.shape, "Dimensions:", one_d.ndim)

print("\n2D Array:\n", two_d)
print("Shape:", two_d.shape, "Dimensions:", two_d.ndim)

print("\n3D Array:\n", three_d)
print("Shape:", three_d.shape, "Dimensions:", three_d.ndim)

1D Array:
 [1 2 3 4 5]
Shape: (5,) Dimensions: 1

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3) Dimensions: 2

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2) Dimensions: 3


In [28]:
import numpy as np

array = np.random.randint(1, 100, (5, 5))

print("5x5 Random Integer Array:\n", array)

print("\nElement at row 2, column 3:", array[1, 2])
print("First row:", array[0])
print("Last column:", array[:, -1])
print("Subarray (rows 2-4, columns 1-3):\n", array[1:4, 0:3])

5x5 Random Integer Array:
 [[19 86 21 20  2]
 [40 86 52 54 69]
 [59 92 13 80 34]
 [43 42 75  5  4]
 [40 62 12  6 66]]

 52ment at row 2, column 3:
First row: [19 86 21 20  2]
Last column: [ 2 69 34  4 66]
Subarray (rows 2-4, columns 1-3):
 [[40 86 52]
 [59 92 13]
 [43 42 75]]


In [29]:
import numpy as np

array = np.arange(1, 17).reshape(4, 4)

print("Original 4x4 Array:\n", array)

print("\nFirst two rows:\n", array[:2])
print("\nLast two columns:\n", array[:, -2:])
print("\nSubarray (middle 2x2 block):\n", array[1:3, 1:3])
print("\nElements from second and fourth row, first and third column:\n", array[[1, 3], [0, 2]])

Original 4x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First two rows:
 [[1 2 3 4]
 [5 6 7 8]]

Last two columns:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]

Subarray (middle 2x2 block):
 [[ 6  7]
 [10 11]]

Elements from second and fourth row, first and third column:
 [ 5 15]


In [30]:
import numpy as np

array_2d = np.arange(1, 13).reshape(6, 2)
array_3d = array_2d.reshape(2, 3, 2)
flattened_array = array_3d.flatten()

print("Original 2D Array (6x2):\n", array_2d)
print("\nReshaped 3D Array (2x3x2):\n", array_3d)
print("\nFlattened Array:\n", flattened_array)

Original 2D Array (6x2):
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Reshaped 3D Array (2x3x2):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Flattened Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_1d = np.array([10, 20, 30])

result = array_2d + array_1d

print("Original 2D Array:\n", array_2d)
print("\n1D Array:\n", array_1d)
print("\nResult After Broadcasting:\n", result)

Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

1D Array:
 [10 20 30]

Result After Broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [32]:
import numpy as np

A = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

addition = A + B
subtraction = A - B
multiplication = A * B
division = A / B

print("Element-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)
print("\nElement-wise Division:\n", division)

Element-wise Addition:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]

Element-wise Subtraction:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Element-wise Multiplication:
 [[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]

Element-wise Division:
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [33]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Math": [85, 78, 92],
    "Science": [88, 74, 95],
    "English": [90, 80, 85]
}

df = pd.DataFrame(data)

df["Total"] = df["Math"] + df["Science"] + df["English"]

def assign_grade(total):
    if total >= 270:
        return "A"
    elif total >= 240:
        return "B"
    elif total >= 210:
        return "C"
    else:
        return "D"

df["Grade"] = df["Total"].apply(assign_grade)

print(df)

      Name  Math  Science  English  Total Grade
0    Alice    85       88       90    263     B
1      Bob    78       74       80    232     C
2  Charlie    92       95       85    272     A


In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("RB") 
print(df.head())
average_conversations = df["Interaction_Count"].mean()
print(f"Average Daily Conversations: {average_conversations}")
total_steps = df["Steps_Walked"].sum()
print(f"Total Steps Walked: {total_steps}")
max_energy = df["Energy_Consumption (kWh)"].max()
min_energy = df["Energy_Consumption (kWh)"].min()
print(f"Maximum Energy Consumption: {max_energy} kWh")
print(f"Minimum Energy Consumption: {min_energy} kWh")
correlation = df["Steps_Walked"].corr(df["Energy_Consumption (kWh)"])
print(f"Correlation between Steps Walked and Energy Consumption: {correlation}")
plt.figure(figsize=(12, 5))
sns.histplot(df["Objects_Recognized"], bins=10, kde=True, color='blue')
plt.title("Distribution of Objects Recognized Daily")
plt.xlabel("Objects Recognized")
plt.ylabel("Frequency")
plt.grid(True)
plt.show()
plt.figure(figsize=(6, 4))
sns.boxplot(y=df["Objects_Recognized"], color="orange")
plt.title("Box Plot of Objects Recognized")
plt.ylabel("Objects Recognized")
plt.grid(True)
plt.show()
learning_sessions_variance = df["Learning_Sessions"].var()
print(f"Variance in Learning Sessions: {learning_sessions_variance}")

<class 'ModuleNotFoundError'>: No module named 'seaborn'